name: tranX
channels:
  - anaconda
  - defaults
dependencies:
  - cudatoolkit=10.1.168=0
  - cudnn=7.6.0=cuda10.1_0
  - cupti=10.1.168
  - python=3.7.3
  - pip:
    - compare-mt==0.2.7
    - elasticsearch==7.0.5
    - six==1.12.0
    - xgboost==0.90
    - torch==1.0.1.post2
    - tqdm